import Head from 'next/head'
import { useState } from 'react'
import { Dialog } from '@headlessui/react'

export default function Home() {
  let [isOpen, setIsOpen] = useState(true)

  return (
    <>
      <Head>
        <title>Bootstrap SaaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h1 className='text-3xl text-bold text-gray-800 text-center'>Hi Everyone!</h1>
        <h2 className='text-xl text-bold text-gray-600 text-center'>Welcome to the Bootstrap SaaS Project!</h2>


        <Dialog 
          open={isOpen} 
          onClose={() => setIsOpen(false)}
          className="relative z-50">
            <div className="fixed inset-0 bg-black/30" aria-hidden="true" />
            <div className="fixed inset-0 flex items-center justify-center p-4">
              <Dialog.Panel className="w-full max-w-sm rounded bg-white">
                <Dialog.Title>Deactivate account</Dialog.Title>
                <Dialog.Description >
                  This will permanently deactivate your account
                </Dialog.Description>

                <p>
                  Are you sure you want to deactivate your account? All of your data
                  will be permanently removed. This action cannot be undone.
                </p>

                <button onClick={() => setIsOpen(false)}>Deactivate</button>
                <button onClick={() => setIsOpen(false)}>Cancel</button>
              </Dialog.Panel>
            </div>
        </Dialog>
      </main>
    </>
  )
}
